morepost/urls.py
from django.conf.urls import url
from morepost import views
from django.urls import path

app_name ='morepost'

urlpatterns = [
    
    url(r'^dayend/',views.dayend,name='dayend'),
    url(r'^java/dayend/',views.dayend,name='dayend'),
    url(r'^test/dayend/',views.dayend,name='dayend'),

]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from post import views
from django.conf.urls import url
from django.conf.urls import include



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^',include('post.urls')),
    url(r'^',include('morepost.urls')) 
]

post/urls.py
from django.conf.urls import url
from post import views
from django.urls import path

app_name ='post'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^java/',views.java,name='java'),
    url(r'^python/',views.pythons,name='pythons'),
    url(r'^test/',views.tests,name='tests'),
    url(r'^follow/',views.formes,name='formes')

]

morepost/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

class Catagory(models.Model):
    cat_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.cat_name

class Post(models.Model):
    catagory = models.ForeignKey(Catagory,on_delete=models.CASCADE)
    count = models.CharField(max_length=10000000000000,unique=True)
    date = models.DateField()
    title = models.CharField(max_length=264,unique=True)
    img_name = models.CharField(max_length=100,unique=True)
    text = models.CharField(max_length=3500,unique=True)

    def __str__(self):
        return self.title

class Visiters(models.Model):
    name = models.CharField(max_length=254)
    email = models.EmailField(max_length=254,unique=True)
    
    def __str__(self):
        return self.name

post/forms.py
from django import forms
from post.models import Visiters

class VisiterEmail(forms.ModelForm):
    class Meta:
        model = Visiters
        fields = '__all__'

morepost/views.py
from django.shortcuts import render

# Create your views here.

def dayend(request):
    return render(request,'fullpost/dayendsale/dayendsale.html')

post/views.py
from django.shortcuts import render
from post.models import Catagory,Post
from post.forms import VisiterEmail
from django.views import View
from django.utils import timezone
# Create your views here.

# this is a catagory section

def index(request):
    webpage_post = Post.objects.order_by('date').reverse()[0:]
    my_post = {'all_post':webpage_post}
    return render(request,'allpost/post.html',context = my_post)

def java(request):
    webpage_post = Post.objects.order_by('date').reverse()[0:]
    my_post = {'java_post':webpage_post}
    return render(request,'catpost/javaonly/javaonly.html',context = my_post)

def pythons(request):
    webpage_post = Post.objects.order_by('date').reverse()[0:]
    my_post = {'python_post':webpage_post}
    return render(request,'catpost/pythononly/python.html',context = my_post)

def tests(request):
    webpage_post = Post.objects.order_by('date').reverse()[0:]
    my_post = {'test_post':webpage_post}
    return render(request,'allpost/test.html',context = my_post)

# this is a form section


def formes(request):
    form = VisiterEmail()
    if request.method == 'POST':
        form = VisiterEmail(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('this is a wrong')
    return render(request,'userform/visiterform.html',context={'form':form})

# social media section



# this is a full form section

templates/allpost/post.html
<!DOCTYPE html>

{% extends 'base/base.html' %}

    {% block body_block %}

    
      {% for pos in all_post %}
             
        <p></p>
        <div class="jumbotron bg-dark text-light">
          <h1 class="display-4">{{ pos.title }}</h1>
          <p>{{ pos.date }}</p>
          <p class="lead"></p>
          <img class="card-img-top" src="\static\images\post\{{ pos.img_name }}" alt="image not found">
          <hr class="my-4">
          <p>{{ pos.text }}</p>
          <a class="btn btn-primary btn-lg" href="{{ pos.count }}" role="button">See more</a>
        </div>
  
      {% endfor %}

    {% endblock %}

templates/allpost/test.html
<!DOCTYPE html>

{% extends 'base/base.html' %}

    {% block body_block %}

    
      {% for pos in test_post %}
      
            
        <p></p>
          <div class="jumbotron col-md-12 bg-dark text-light">
            <h1 class="display-4">{{ pos.title }}</h1>
            <p>{{ pos.date }}</p>
            <p class="lead">{{ pos.text }}</p>
            <img class="card-img-top" src="\static\images\post\{{ pos.img_name }}" alt="image not found">
            <hr class="my-4">
            <p></p>
            <a class="btn btn-primary btn-lg" href="{{pos.count}}" role="button">Learn More</a>
          </div>


      {% endfor %}

    {% endblock %}

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>www.milankaviranga.com</title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/mysyle.css' %}">
    </head>
    
    <body>

        <!--<div class="container">-->
          <header id="upheaders">
            
            <div class="container"><h4><a id="social" href="https://www.facebook.com">Facebook</a> <a id="social" href="http://www.github.com">Github</a> <a id="social" href="http://www.Linkdin.com">Linkdin</a></h4></div>
            
          </header>
        </div>  

        <p></p>

        <h1 id="upheader"><div class="container"><center>MILAN BLOG</center></div></h1>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-left sticky-top">
        
          <a class="navbar-brand" href="{% url 'post:index' %}">HOME</a>
  
  
          <button class="navbar-toggler" type='button' data-toggle='collapse' data-target='#collapsibleNavbar'>
            <span class='navbar-toggler-icon'></span>
          </button>
  
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
      
  
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link text-light" href="#">CONTACT</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="#">ABOUT</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown">
                  CATAGORY
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'post:pythons' %}">$ PYTHON</a>
                  <a class="dropdown-item" href="{% url 'post:java' %}">$ JAVA</a>
                </div>
              </li>
              <li class="nav-item" id="line">
                <button class="btn btn-danger"><a id="btna" href="{% url 'post:formes' %}">Follow</a></button>
              </li>
            
            </ul>

          </div>
  
        </nav>

        <div class="content">
          <div class="container">
            {% block body_block %}
            {% endblock %}
          </div>
        </div>
        
      

      <script src="{% static 'bootstrap/jq/jquary slim.js' %}"></script>
      <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
        
      
    </body>
</html>

templates/catpost/javaonly/javaonly.html
<!DOCTYPE html>

{% extends 'base/base.html' %}

    {% block body_block %}

    
         {% for pos in java_post %}

            {% if pos.catagory.cat_name == 'java'  %}
                              
            <p></p>
            <div class="jumbotron bg-dark text-light">
              <h1 class="display-4">{{ pos.title }}</h1>
              <p>{{ pos.date }}</p>
              <p class="lead"></p>
              <img class="card-img-top" src="\static\images\post\{{ pos.img_name }}" alt="image not found">
              <hr class="my-4">
              <p>{{ pos.text }}</p>
              <a class="btn btn-primary btn-lg" href="{{ pos.count }}" role="button">See more</a>
            </div>
            {% endif %}

         {% endfor %}

    {% endblock %}

templates/catpost/pythononly/python.html
<!DOCTYPE html>

{% extends 'base/base.html' %}

    {% block body_block %}

    
         {% for pos in python_post %}

            {% if pos.catagory.cat_name == 'python'  %}
                              
            <p></p>
            <div class="jumbotron bg-dark text-light">
              <h1 class="display-4">{{ pos.title }}</h1>
              <p>{{ pos.date }}</p>
              <p class="lead"></p>
              <img class="card-img-top" src="\static\images\post\{{ pos.img_name }}" alt="image not found">
              <hr class="my-4">
              <p>{{ pos.text }}</p>
              <a class="btn btn-primary btn-lg" href="{{ pos.count }}" role="button">See more</a>
            </div>
            {% endif %}

         {% endfor %}

    {% endblock %}

templates/fullpost/dayendsale/dayendsale.html
<html>
{% load static %}
    <head>
        <title></title>
        <link rel="stylesheet" href="{% static 'fullpost/dayendsale/css/dayendsale.css' %}">
        <link rel="stylesheet" href="{% static 'fullpost/dayendsale/css/bootstrap.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                  <h1 id="title">Day End Sale Application</h1>
                  <br>
                  <h4>THIS IS A MY FIRST APPLICATION</h4>
                  <br>
                  <img class="card-img-top" src="{% static 'fullpost\dayendsale\images\pythondaysale.jpg' %}">
                  <br><br>
                  <p>This Application use for the Find a Day End sales in Stores. 
                      This is Create by Using Python Programming Language and Tkinter library. 
                      Tkinter (pronounced tea-kay-inter) is the Python interface to Tk, the GUI toolkit for Tcl/Tk. Tkinter, the built-in graphical user interface (GUI) library for all standard Python distributions.
                      Click the See More and look at the code.
                  </p>
                  <ul>
                      <li>Core Programming language - Python </li>
                      <li>Use Moduls - Tkinter </li>
                  </ul>
                  <a class="btn btn-danger btn-md" href="#" role="button">See the Code</a>
                  <a class="btn btn-primary btn-md " href="{% url 'post:index' %}" role="button" style="float:right;">Back To Home</a>
                </div>
              </div>
        </div>
    </body>
</html>

templates/userform/visiterform.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/mystyle.css' %}">
    </head>
    <body>


        <div class="container">
            <p></p>
            <br><br><br>
            <div class="jumbotron">
                <p></p>
                <h1 class="display-4">FOLLOW FORM</h1>
                <br><br>
                <form class="visiterform" method="POST">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">Submit</button>
                </form>
            </div>
        </div>
         


        
        <script src="{% static 'bootstrap/jq/jquary slim.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    </body>
</html>